[default]
# Model name
LLM = "openai/gpt-oss-20b"
EMBEDDING_MODEL = "text-embedding-3-small"

# Prompt paths
ROUTER_PROMPT = "prompts/router.md"
GENERAL_PROMPT = "prompts/general.md"
ORDER_PROMPT = "prompts/order.md"
PRODUCT_PROMPT = "prompts/product.md"
AGGREGATOR_PROMPT = "prompts/aggregator.md"
SUMMARY_PROMPT = "prompts/summary.md"

# Data paths
PRODUCT_DATA_PATH = "data/products.csv"
ORDER_DATA_PATH = "data/orders.csv"
INVENTORY_DATA_PATH = "data/inventory.csv"
FAQ_DATA_PATH = "data/faqs.json"

# postgres connection string
DB_URI = "postgresql://postgres:admin123@localhost:5432/agent_db" #postgresql://[user]:[password]@[host]:[port]/[database name]